# ==========已完成==========
###
GET http://localhost:8080/admin/allUsers

# 用户信息查询，
###
GET http://localhost:8080/api/user?name=root

# 登录请求
###
POST http://localhost:8080/login?username=root&password=123

# 个人所拥有的权限，无需admin权限便可查询
###
GET http://localhost:8080/user/deleteFile



# 添加一个权限，需admin权限才可操作
###
POST http://localhost:8080/admin/addPerm
Content-Type: application/json

{
  "username": "admin",
  "permissionId": "2-2",
  "permissionName": "删除文件",
  "permissionUrl": "/file/delete",
  "permissionPerms": "file:delete",
  "createTime": null,
  "updateTime": null,
  "lastLoginTime": null
}



### ====================未完成====================

###
# 他人所拥有的权限，需admin权限才可查询
GET http://localhost:8080/admin/scanOthers?name=admin

###
# /user/add
GET http://localhost:8080/user/deleteFile
